### PR TITLE
Resolve "Create TriBITS Build Alongside Raw CMake Build"

### PR DESCRIPTION
**Pull request by jmgate**
This is a WIP PR to address #171.  Not ready for review or merge.

### CODE REVIEW

**Comment by kuberry** [comment]
Hi @jmgate, we have a condition where either CUSOLVER+CUBLAS will be needed, BLAS+LAPACK, or MKL. All of these are optional, but at least one of these sets of tools must be available. I think we need to verify the user has some combination that will work, but we can't specify what combination that would be (although for Cuda, it does imply CUBLAS).

**Comment by jmgate** [comment]
@kuberry, this is ready for you to play around with.  To test things out, I'd:
1. Merge #176 into `master`.
1. Rebase this branch on top of `master`.
1. Create a branch off of `develop` in Trilinos.
1. `mkdir -p packages/compadre`.
1. In the Compadre root, `./scripts/snapshot_into_trilinos.py --trilinos-dir /path/to/Trilinos`.
1. Create a build directory.
1. Modify the `trilinos-config.sh` to fill in the appropriate paths.
1. Run that script, `make`, and `ctest`.
1. Adjust settings in `CMakeLists.txt` until the tests pass.

Let me know when things look good on your end, because there's one more file we need to tweak in Trilinos when we do the initial snapshot.

**Comment by kuberry** [comment]
Hi @jmgate, I'm just going to drop a list here of things we discussed:

- [ ] Ability to move files from copied location in compadre folder in Trilinos/packages and create an additional commit to that effect during snapshotting
- [ ] Dealing with either LAPACK+BLAS, or MKL, or CUBLAS+CUSOLVER (as long as 1 of 3 is available)
- [ ] Mpiexec shouldn't be called to run examples. All examples/tests in repo are single processor (OpenMP for multicore)
- [ ] I will try to get Compadre_Config.h.in to be produced automatically
- [ ] I will put glob in for src header/source files
- [ ] I will make Version.cmake to be version used by CMakeLists.txt for raw CMake build

I'll add more as I think of them.

**Comment by jmgate** [comment]
For the mpiexec bit, with `tribits_add_test()` you can specify the number of cores to use with `NUM_MPI_PROCS 1`.

BTW, I just rebased this on top of `master` so it's all up-to-date.

**Comment by kuberry** [comment]
If the only two files needed in the root of the repo are Version.cmake and TPLLists.cmake, then I'll mark "Ability to move files from copied location in compadre folder in Trilinos/packages and create an additional commit to that effect during snapshotting" as done. I'm going to reuse Version.cmake, so it can stay there. For TPLLists.cmake, I'll probably add a commented out section in there later explaining the dependencies of the package and how the code is for Trilinos, but how a user can specify these needed things if they using a raw CMake build.

**Comment by kuberry** [comment]
Most recent commit eb4ecec should pass all tests for MPI or serial build of package in Trilinos.

**Comment by kuberry** [comment]
Commit 54ab2b2 handles Compadre_USE_LAPACK, Compadre_USE_MKL, and Compadre_USE_CUDA options (Compadre_USE_LAPACK is default) and will ensure that the correct TPLs are turned on or else will cause Compadre package in Trilinos to be disabled.

**Comment by jmgate** [comment]
Yup, this all looks good on my system as well.  Thanks for figuring out the last few hurdles, @kuberry.  Merge if you're happy with it.

**Comment by kuberry** [comment]
Thanks @jmgate for all of your hard work putting this together!

**Pull request merged**
